# This is a basic workflow to help you get started with Actions

name: greetings

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests
      - name: Run judge
        run: |
          python scripts/welcomeJudge.py result.out
      - name: Save result
        run: |
          cat result.out
          echo "RESULT=`head -1 result.out`" >> $GITHUB_ENV
          tail -5 result.out > result2.out
      - name: comment
        uses: actions/github-script@v4
        with:
          script: |
                const fs = require('fs');
                var text = fs.readFileSync('result2.out', 'utf8');
                github.issues.createComment({ 
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: "👍"+text
                });
                github.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: [ "JudgePR" ] 
                });
            
