# This is a basic workflow to help you get started with Actions

name: comment

on: [pull_request]
    
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: github-actions-up-and-running/pr-comment@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message: Nice PR!👍 Please regist comment with Command [run (path)]
